### ISSUE TITLE
Error: Objects are not valid as a React child (found: object with keys {children}). If you meant to render a collection of children, use an array instead.

### ISSUE THREAD

**Issue by max107** [icode247/Trello-Clone-ReactDnD#1]
Error: Objects are not valid as a React child (found: object with keys {children}). If you meant to render a collection of children, use an array instead.

**Comment by Kevin-Heleodoro** [comment]
I was able to solve this issue by modifying CardItem.jsx 

```
const [{ isDragging }, drag] = useDrag({
		item: { ...item, index },
		type: ITEM_TYPES,
		collect: (monitor) => ({
			isDragging: monitor.isDragging(),
		}),
	});
```

Still having issues with getting the cards to actually drop however.

**Comment by brvangarcia** [comment]
@Kevin-Heleodoro Did you manage to make the cards drop? I'm having a TypeError: item is undefined

**Comment by Kevin-Heleodoro** [comment]
We got it working after a while, this was the final code for the drag:

```
const [{ isDragging }, drag] = useDrag({
        type: 'card',
        item: { id },
        collect: (monitor) => ({
            isDragging: monitor.isDragging(),
        }),
    });
```

Here's a link to where we used it:
https://github.com/MCSP-10/blueocean/blob/main/front-end/src/Applications/ApplicationsBoard/Card.jsx 

Let me know if that helped at all.
